version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "50010:50010"
    volumes:
      - ./instance:/app/instance
      - ./uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped 